// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAU1NwZB7PzWfBXhswf9mOrsgKJYbcbBGE',
    appId: '1:500627702907:web:7e3ecca3a8f06568a58ede',
    messagingSenderId: '500627702907',
    projectId: 'crud-ops-d27ba',
    authDomain: 'crud-ops-d27ba.firebaseapp.com',
    storageBucket: 'crud-ops-d27ba.firebasestorage.app',
    measurementId: 'G-KKPXQZXPKK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBj1eelJgRPKcVjK8z1fiHYaoTRDkTSIs',
    appId: '1:500627702907:android:b610232694fe2f81a58ede',
    messagingSenderId: '500627702907',
    projectId: 'crud-ops-d27ba',
    storageBucket: 'crud-ops-d27ba.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALnzF_VooTMNiKvu9UaYW_R8ePBRS_Jhg',
    appId: '1:500627702907:ios:ee3a81598af257d0a58ede',
    messagingSenderId: '500627702907',
    projectId: 'crud-ops-d27ba',
    storageBucket: 'crud-ops-d27ba.firebasestorage.app',
    iosBundleId: 'com.example.crudfirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALnzF_VooTMNiKvu9UaYW_R8ePBRS_Jhg',
    appId: '1:500627702907:ios:ee3a81598af257d0a58ede',
    messagingSenderId: '500627702907',
    projectId: 'crud-ops-d27ba',
    storageBucket: 'crud-ops-d27ba.firebasestorage.app',
    iosBundleId: 'com.example.crudfirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAU1NwZB7PzWfBXhswf9mOrsgKJYbcbBGE',
    appId: '1:500627702907:web:e07ee5e001db8334a58ede',
    messagingSenderId: '500627702907',
    projectId: 'crud-ops-d27ba',
    authDomain: 'crud-ops-d27ba.firebaseapp.com',
    storageBucket: 'crud-ops-d27ba.firebasestorage.app',
    measurementId: 'G-ERPJL039EF',
  );
}
